name: Build-nuget
run-name: lr

on: 
  push:
   branches:
    - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2019
    steps:
    
    -  name: Check out Code
       uses: actions/checkout@v2
       
    -  name: Add msbuild path to PATH
       uses: microsoft/setup-msbuild@v1.1
       
    -  name: Restore my solution nuget packages
       run: nuget restore WebApplication/WebApplication.sln
       
    -  name: Build my Web Code
       run: msbuild WebApplication/WebApplication.sln /p:Configuration=Release /p:DeployTarget=Package /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeployOnBuild=true
       
    -  name: Build my Sql code
       run: msbuild WebApplication/Database1/Database1.sqlproj
       
    -  name: Upload my build artifacts
       uses: actions/upload-artifact@v3.1.2
       with:
        name: build_artifact
        path: '**/obj/Release/Package/**'
  
#   deploy-my-appservice:
#     needs: build-my-C-code-job
#     runs-on: windows-2019
#     steps:
#       - name: Run Azure webapp deploy action
#         uses: Azure/webapps-deploy@v2.2.4
#         with:
#           app-name: testappservice
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
#           package: '**/obj/Release/Package/**'
        
